Adjusted font size in trainings constructions
claassenlab/cellpose pull request #14
Opened 2024-05-10 22:19 UTC by RukiyyeE

Resolves https://github.com/claassenlab/cellpose/issues/3

2024-05-13 23:06 UTC, RenzoRichter requested changes
Hey there, great job. 

## MAIN-Review:
 Alle Anforderungen aus dem Issue sind erfüllt (⇒ code implementiert Issue [#3  ])

Code compiles und die Menüs funktionieren. 
Auch mehrere Menüs gleichzeitig offen scheinen gut zu funktionieren.

_______________________________________
## Nitpicks

Fügt vielleicht noch ein paar extra Kommentare ein, um die Lesbarkeit noch weiter zu steigern.

Außerdem setzt bitte die vorgeschlagenen Änderungen noch in die Tat um,
siehe Review-Kommentare.

______________________________________
### File can not yet be merged to main!

2024-05-13 23:06 UTC, RenzoRichter commented on cellpose/gui/guiparts.py
> +Copyright Â© 2023 Howard Hughes Medical Institute, Authored by Carsen Stringer and Marius Pachitariu.
Warum hier Â

2024-05-13 23:06 UTC, RenzoRichter commented on cellpose/gui/guiparts.py
> -        self.parameter_explanations = ["The learning rate determines how quickly or slowly the model learns from data. A higher learning rate may lead to faster learning but could cause the model to
Note to self: Wurde hinzugefügt in PR #9

2024-05-13 23:06 UTC, RenzoRichter commented on cellpose/gui/guiparts.py
> -            qlabel.setToolTip(self.parameter_explanations[i])
Note to self: Wurde hinzugefügt in PR #9

2024-05-13 23:06 UTC, RenzoRichter commented on cellpose/gui/guiparts.py
> +        self.font_size_combo.currentIndexChanged.connect(self.adjust_font_size)
Die Line `self.font_size_combo.currentIndexChanged.connect(self.adjust_font_size)` braucht am besten noch ein erklärender Kommentar 
⇒ Sonst ein bisschen unverständlich
z.B.:
```
# Diese Zeile verbindet das Signal "currentIndexChanged" des QComboBox-Objekts "self.font_size_combo" mit der Methode "self.adjust_font_size".
# Das bedeutet, dass jedes Mal, wenn der aktuell ausgewählte Index in "self.font_size_combo" geändert wird (z.B. durch Benutzerinteraktion), 
# die Methode "self.adjust_font_size" automatisch aufgerufen wird.
```
Gerne auch noch ein bisschen gekürzt :)

2024-05-13 23:06 UTC, RenzoRichter commented on cellpose/gui/guiparts.py
> +if __name__ == "__main__":
Was wird hier genau gemacht? 
Kommentar z.B.:
```
# Dieser Code startet die TrainHelpWindow-Anwendung, wenn das Skript direkt ausgeführt wird.
# Das TrainHelpWindow ist ein Dialogfenster, welches es dem Nutzer ermöglicht ???
```

2024-05-13 23:06 UTC, RenzoRichter commented on cellpose/gui/guiparts.py
> +        self.font_size_combo.addItems([str(size) for size in range(5, 30, 3)])
Menü geht nur bis 29, wenn man in 3er-Schritten von 5 hochgeht.

2024-05-13 23:06 UTC, RenzoRichter commented on cellpose/gui/guiparts.py
> +        self.label = QLabel(text)
Setzt das `label` vielleicht von Beginn an auf eine sinnvolle Schriftgröße z.B. 17
z.B.:
`label.setFont(QtGui.QFont("Arial", 17))`

2024-05-17 16:51 UTC, jakobjo requested changes
Hi, echt gute Arbeit, die gewünschten Punkte sind implementert und funktionieren fast einwandfrei (s. Kommentar). Ich nehme mal an, dass ihr nicht jedes Leerzeichen selbst gesetzt habt hinter den Hastags der Kommentar, aber solche Veränderungen machen die eigentlichen Änderungen etwas unübersichtlich (Vielleicht wurde das irgendwie automatisch gemacht?).  

Wenn ihr Fragen habt was genau für ein Problem mit dem automatischen Anpassen vorliegt kontaktiert mich gerne. 

Ansonsten würde ich mich den Punkten von Henry anschließen, vor allem die default Fontsize zu erhöhen.

2024-05-17 16:51 UTC, jakobjo commented on cellpose/gui/guiparts.py
> +from tkinter import ttk
Werden diese tkinter imports genutzt?

2024-05-17 16:51 UTC, jakobjo commented on cellpose/gui/guiparts.py
> +        new_font_size = max(5, int(self.height() / 30))
Das ist eine gute Umsetzung, echt stark.

Beim skalieren der Schriftgröße sollte allerdings auch die Breite des Fensters berücksichtigt werden, da es sonst bei einem schmalen aber hohen Fenster und großer Schriftgröße selbts adjustziert (und das gerade zu explosionsartig). Ich habe ein bisschen rumprobiert und vermute, dass QT beim resizen immer versucht den gesamten Text des Labels darzustellen und deshalb das Fenter nach unten erweitert. 

Um das zu verhindern, könnte man eventuell die Berechnung der new_font_size anpassen und auch von der Breite des Fensters abhängig machen, da sonst bei großer Schrift die Größe als angemessen erachtet wird obwohl das Fenster zu schmal ist. Andere Idee wäre sonst, da Fenster in einem festen Verhältnis nur anpassbar zu machen (z.B. 16:9), aber der erste Weg wäre auf jedenfall optimaler.

2024-05-17 16:51 UTC, jakobjo commented on cellpose/gui/guiparts.py
> +        layout.addWidget(self.font_size_combo, 1, 0, 1, 1)
Die Kombobox ist etwas groß am unteren Fensterrand.

2024-05-17 17:56 UTC, RukiyyeE commented
> Hi, echt gute Arbeit, die gewünschten Punkte sind implementert und funktionieren fast einwandfrei (s. Kommentar). Ich nehme mal an, dass ihr nicht jedes Leerzeichen selbst gesetzt habt hinter den Hastags der Kommentar, aber solche Veränderungen machen die eigentlichen Änderungen etwas unübersichtlich (Vielleicht wurde das irgendwie automatisch gemacht?). Wenn ihr Fragen habt was genau für ein Problem mit dem automatischen Anpassen vorliegt kontaktiert mich gerne.
> 
> Zudem würde ich die default Fenstergröße etwas erhöhen und eine minimale Größe festlegen.
> 
> Ansonsten würde ich mich den Punkten von Henry anschließen, vor allem die default Fontsize zu erhöhen.

Danke für euren Review. Die Leerzeichen habe ich auch erst nach dem pushen bemerkt. Sollen die Leerzeichen Rückgängig gemacht werden oder soll es diesmal so bleiben?

2024-05-17 18:20 UTC, RukiyyeE commented on cellpose/gui/guiparts.py
> +        self.font_size_combo.addItems([str(size) for size in range(5, 30, 3)])
Ist das hier also so in Ordnung?

2024-05-17 18:23 UTC, jakobjo commented
> > Hi, echt gute Arbeit, die gewünschten Punkte sind implementert und funktionieren fast einwandfrei (s. Kommentar). Ich nehme mal an, dass ihr nicht jedes Leerzeichen selbst gesetzt habt hinter den Hastags der Kommentar, aber solche Veränderungen machen die eigentlichen Änderungen etwas unübersichtlich (Vielleicht wurde das irgendwie automatisch gemacht?). Wenn ihr Fragen habt was genau für ein Problem mit dem automatischen Anpassen vorliegt kontaktiert mich gerne.
> > Zudem würde ich die default Fenstergröße etwas erhöhen und eine minimale Größe festlegen.
> > Ansonsten würde ich mich den Punkten von Henry anschließen, vor allem die default Fontsize zu erhöhen.
> 
> Danke für euren Review. Die Leerzeichen habe ich auch erst nach dem pushen bemerkt. Sollen die Leerzeichen Rückgängig gemacht werden oder soll es diesmal so bleiben?

Gerne kurz rückgängig machen, dann gibts beim mergen da keine Probleme.

2024-05-18 13:37 UTC, mariehartung commented on cellpose/gui/guiparts.py
> +        self.label = QLabel(text)
Ich glaube, das ist aber eh das Fenster für allgemein help, nicht das für uns. Das lässt sich aber soweit ich das sehe sowieso nicht öffnen (unabhängig von unserem Code). Wir erhöhen die default Größe aber auf jeden Fall mal bei uns.

2024-05-20 09:50 UTC, jakobjo commented on cellpose/gui/guiparts.py
> +        new_font_size = max(5, max(int(self.height() / 50), int(self.width() / 60)))
Das funktioniert leider immer noch nicht, das zuvor beschriebene Problem besteht weiterhin. Ich schicke euch mal ein Video auf Discord um euch zu zeigen was ich meine.

2024-05-25 07:33 UTC, RenzoRichter approved these changes
Hey there, great job.

# MAIN-Review:
Alle Anforderungen aus dem Issue sind erfüllt (⇒ code implementiert Issue [#3  ])

Code compiles und die Menüs funktionieren.
Auch mehrere Menüs gleichzeitig offen scheinen gut zu funktionieren.

---

# Nitpicks
Fügt vielleicht noch ein paar extra Kommentare ein, um die Lesbarkeit noch weiter zu steigern.

---

## File can be merged to main!

2024-05-27 14:49 UTC, jakobjo approved these changes
## Main Review

Das implentierte Feature erfüllt alle gewünschten Bedingungen aus  Issue #3.
Die Startschriftgröße und Fenstergröße wurden auf einen sinnvollen Wert angepasst und der Text passt sich dynamisch mit der Fenstergröße an. Ebenso funktioniert die Schriftgrößenauswahl durch den User selbst.

## Requested Changes

Alle geforderten Veränderungen wurden implementiert, die Fenstergröße lässt sich nun ohne Probleme anpassen und die Startgröße ist gut gewählt.

## Branch can be merged!

Ich weiß nicht genau wie das passiert ist, aber euer Branch wurde auf einem Commit erstellt, der die Änderungen des anderen Scrum Teams bei den Training Prametern bereits enthalten hat. Leider wurden die bei euch wieder verworfen, das wird vermutlich zu einem Konflikt führen, schaut also, dass diese Änderungen erhalten bleiben. (Gemeint ist die Parameter Explanation beim drüberhovern).

Gute Arbeit!

2024-05-29 10:54 UTC, jakobjo approved these changes
Das alte Feature wurde wieder hinzugefügt und funktioniert. Der Branch kann mit dem Mainbranch gemerged werden.

2024-05-29 14:26 UTC, RenzoRichter approved these changes
Feature Text des anderen Features (#5) wurde wieder hinzugefügt. 
Funktionalität besteht weiterhin. 

---
## Der Branch kann auf Main gemerged werden

2024-05-29 15:22 UTC, merged