18 New menu for colour options
claassenlab/cellpose pull request #22
Opened 2024-06-02 17:56 UTC by ShalinGhe

Solves #18

This PR addresses the user story of adding a separate menu on the right side of the Cellpose GUI. The goal is to provide more space for the colour saturation sliders in the future.

Changes made:
1. Added a new menu on the right side of the GUI. This menu matches the width and height of the existing left side menu.
2. Made the right side menu scrollable, similar to the left side menu.
3. Ensured that the right side menu resizes with the window, maintaining its width relative to the left side menu.

Changes were only made in the gui.py file.

2024-06-03 12:06 UTC, Davidundso reviewed
Tested the GUI for the changes:
- Menu on the right looks perfect
- height/width is right
- scollbar is there
- adjusts height with the window
- loading a picture and segmentation worked as before
- the code also looks good and is well commented

I would like to have one more person review this, which is why I only comment this review.

2024-06-03 14:21 UTC, Davidundso approved these changes
Tested the GUI for the changes:
- Menu on the right looks perfect
- height/width is right
- scrollbar is there
- adjusts height with the window
- loading a picture and segmentation worked as before
- the code also is well-structured and is commented helpfully

2024-06-03 15:23 UTC, robertkrasniqi approved these changes
Hab den Code lokal getestet und es lief alles wie es sollte.
Code ist akkurat und gut lesbar.

Good Job :)

2024-06-03 20:27 UTC, JoshuaSchlucke requested changes
Sieht alles mega aus, wenn du nur kurz die letzten 2 zeilen löscht ist es done und kannst es mergen, echt super gemacht

2024-06-03 20:27 UTC, JoshuaSchlucke commented on cellpose/gui/gui.py
> +        self.rightScrollArea.setFixedWidth(leftMenuWidth)
Der Code sieht mega aus und du hast es perfekt so umgesetzt wie es gefragt wurde also mega echt gut ^^ nur leider ist es im ticket ein bisschen falsch beschrieben, wenn du es so machst wie hier dann skaliert es leider nicht mehr dynamisch wenn dinge hinzugefügt werden und dann könnten teile abgeschnitten sein, auch wenn es hässlich aussieht und du dir wahrscheinlich viel mühe gemacht hast ist es wahrscheinlich besser wenn du die letzen 2 zeilen löscht sorry :(

2024-06-04 14:08 UTC, JoshuaSchlucke approved these changes
Sieht super aus, good job :)

2024-06-04 15:15 UTC, sonjajk approved these changes
Ich kann mich den anderen nur anschließen. Es sieht top aus und scheint alles wie geplant zu funktionieren

2024-06-04 16:10 UTC, merged