The colour sliders are on the right hand side now
claassenlab/cellpose pull request #23
Opened 2024-06-05 08:08 UTC by sonjajk

We moved the color sliders to the right-hand side, as requested in #19. To accomplish this, we 
- relocated them from the left-hand side 
- to the right-hand side 
- and adjusted the formatting to ensure there are no leftover spaces.

2024-06-05 08:59 UTC, JoshuaSchlucke requested changes
Mega das ging ja voll schnell und sieht schoneinmal super aus, habe nur ein paar kleinigkeiten wegen inline commentaren bemerkt ansonsten sieht es echt gut aus, aber kann der slider vielleicht ein bisschen breiter sein? Es sieht jetzt schon mega aus aber wäre vllt bisschen einfacher zu bedienen

2024-06-05 08:59 UTC, JoshuaSchlucke commented on cellpose/gui/gui.py
> +from PyQt5.QtWidgets import QLabel, QSlider, QVBoxLayout, QWidget
Schau mal inn zeile 10 da sind die imports schon mal aufgelistet

2024-06-05 08:59 UTC, JoshuaSchlucke commented on cellpose/gui/gui.py
> +        #b = self.make_buttons() was here
Immer alten code löschen, generell niemals code auskommentieren das wird ab den nächsten wochen dann die tests fehlschlagen lassen

2024-06-05 08:59 UTC, JoshuaSchlucke commented on cellpose/gui/gui.py
> +        for r in range(3):  # changed to right box and to variable c
Nie im code sagen was verändert wurde sondern was der code versucht zu erreichen

2024-06-06 19:18 UTC, JoshuaSchlucke approved these changes
Mega sieht super aus, danke dir für die anpassungen es sieht echt gut aus

2024-06-07 06:31 UTC, robertkrasniqi approved these changes
Ich habe den Code lokal getestet. Die Kriterien des Issues sind erfüllt, links ist nicht´s "frei" gelassen und rechts wurden die Slider in einer geeigneten Größe eingefügt. Diese funktionieren auch immer noch. Ich habe mit 2x Bildern getestet, es sind keine Bugs aufgetreten.

Good Job  :)

2024-06-07 06:31 UTC, merged