added initial color to color dialog buttons
claassenlab/cellpose pull request #36
Opened 2024-06-13 14:40 UTC by robertkrasniqi

resolves #25 

Die Buttons haben jetzt initial die Farben Rot, Grün und Blau. Hierfür werden die Werte beim initialisieren der Buttons gesetzt.

Die Arrays colorsnames und names waren m.M.n. unnötig, deshalb habe ich sie gelöscht.

2024-06-13 16:00 UTC, sonjajk requested changes
Die color buttons haben initial die Farben rot, grün und blau, wie angefordert, allerdings öffnet sich der color dialog nach wie vor mit weiß und nicht mit der button color. (Siehe Bild)
![grafik](https://github.com/claassenlab/cellpose/assets/93002386/b45911cf-4fd2-4621-8b11-1dbb7a94cfbc)
Ansonsten ist der Code sehr gut verständlich und dokumentiert :)

2024-06-13 16:06 UTC, JoshuaSchlucke requested changes
Sieht mega aus, nur 2 nitpicks, aber anders schnell, respekt.
Die commit message "-" hast du ausversehen vergessen eine zu schreiben, muss kein roman sein, selbst minor bugfix oder so reicht aus.

2024-06-13 16:06 UTC, JoshuaSchlucke commented on cellpose/gui/gui.py
> +        self.on_off_buttons = [self.create_on_off_button() for _ in range(3)]
Dadurch dass beide die selbe anzahl haben sollten beide auf die selbe variable zugreifen für die anzahl z.B. statt `range(3)` `len(colors)`

2024-06-13 19:12 UTC, robertkrasniqi commented
> Die color buttons haben initial die Farben rot, grün und blau, wie angefordert, allerdings öffnet sich der color dialog nach wie vor mit weiß und nicht mit der button color. (Siehe Bild) ![grafik](https://private-user-images.githubusercontent.com/93002386/339455844-b45911cf-4fd2-4621-8b11-1dbb7a94cfbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMDYyNTYsIm5iZiI6MTcxODMwNTk1NiwicGF0aCI6Ii85MzAwMjM4Ni8zMzk0NTU4NDQtYjQ1OTExY2YtNGZkMi00NjIxLThiMTEtMWRiYjdhOTRjZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDE5MTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4OWRiYzgxMDE3OTkxNGFhNmIyNTgzMjI4ZmRkZGU1YjQ3YTNkZDUxYzU1OGVjN2Q4OTI1ZTVhOGFkNjlhOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KsBo27pWhKy_bT_5W-wW66siM8jyyDh-JelI2sGLgkU) Ansonsten ist der Code sehr gut verständlich und dokumentiert :)

Danke für die schnelle Review und das Feedback :)
Habe gerade nachgeschaut wie es auf anderen Branches war. Also das Verhalten ist normal, die Farbpalette erwartet ja keine Werte, sondern setzt diese lediglich. Soweit ich das sehen kann gibt es auch keine Möglichkeit das zu ändern.

2024-06-13 19:20 UTC, robertkrasniqi commented on cellpose/gui/gui.py
> +        self.on_off_buttons = [self.create_on_off_button() for _ in range(3)]
Okay zukünftig mache ich das so :) (Die Änderung war mir peinlich, da ich was vergessen hatte haha)

Guter Tipp, habs geändert, danke.

2024-06-13 20:33 UTC, JoshuaSchlucke commented
Also wenn du den jetzigen wert auf den wert des buttons setzen willst kannst du setCurrentColor nehmen

https://doc.qt.io/qtforpython-6/PySide6/QtWidgets/QColorDialog.html#PySide6.QtWidgets.QColorDialog.setCurrentColor

2024-06-14 08:03 UTC, robertkrasniqi commented
test

2024-06-14 10:36 UTC, sonjajk approved these changes

2024-06-14 10:37 UTC, sonjajk commented
Genauso hab ich es mir vorgestellt. Super gemacht!

2024-06-15 15:54 UTC, ShalinGhe approved these changes
Hab es jetzt auch lokal getestet und es funktioniert genau wie es sollte! Auch die gewünschten Farben werden im ColourDialog korrekt angezeigt, der Code ist passend zum Umfeld geschrieben und schön kommentiert.
Wenn noch der Request mit der Variable (3 vs len(color)) geschlossen wird dann kann das in meinen Augen gemerged werden

2024-06-16 16:26 UTC, JoshuaSchlucke approved these changes
Sieht super aus danke für den change

2024-06-17 21:54 UTC, merged