34_new_settings_export_option_in_file_menue
claassenlab/cellpose pull request #43
Opened 2024-06-30 05:55 UTC by sonjajk

Ich habe #34 gelöst, indem ich den neuen Menüpunkt "Save Features as .json" hinzugefügt habe und ihn so eingestellt habe, dass er wie die anderen Speicheroptionen nur klickbar ist, wenn ein Bild geladen und verändert wurde(was ich aber auch leicht ändern kann oder an eine andere Bedingung knüpfen kann, falls erforderlich). Wenn diese Bedingungen erfüllt sind und die Option ausgewählt wird, wird ein leeres json-File mit dem Namen "parent.filename_cp_settings.json" abgespeichert, wobei parent.filename der Name der gerade geladenen Abbildung ist. Außerdem wird, wenn eine vorherige Version des json-Files existiert, diese durch das neue ersetzt.

2024-07-01 18:38 UTC, robertkrasniqi approved these changes, later dismissed
Ich habe den Code lokal auf meinem Laptop getestet. Unter "File -> Save Settings as .json" wird eine .json Datei im Hauptverzeichnis des Cellpose Ordners abgelegt die bis auf "{}" leer ist (ich nehme an das soll so sein), siehe Bild unten. Insofern sind alle gefragten Kriterien erfüllt.

Der Code sieht sinnvoll aus und ist gut dokumentiert. 

Good Job :)

<img width="887" alt="image" src="https://github.com/claassenlab/cellpose/assets/148360764/dac4401f-8115-4357-bc5e-e934df72b960">

2024-07-02 07:06 UTC, Davidundso requested changes
Ich habe das feature ausprobiert auf Mac, folgendes funktioniert:
- Im menü "file" ist die neue Option sichtbar
- Wenn eine Segmentierung gemacht wurde kann eine .json datei über den neuen Menüpunkt gespeichert werden
- die Datei wird im richtigen Pfad gespeichert (der Pfad, aus dem das input image stammt)
- Die datei ist richtig bennant

Das funktioniert noch nicht:
- Die .json settings enthalten keine Informationen die erst nach der Segmentierung bekannt sind, deshalb sollten sie auch vor einer Segmentierung schon abgespeichert werden können. Aktuell muss erst segmentiert werden, bevor settings gespeichert werden können.

Ich habe an der Zeile kommentiert, an ich vermute, dass dort die Änderung gemacht werden muss

2024-07-02 07:06 UTC, Davidundso commented on cellpose/gui/gui.py
> +        self.saveSettings.setEnabled(False)
Die settings .json sollte auch ohne Segmentierung gespeichert werden können (darin werden später nur Farbe, Intensität und Gruppierung der Channels gespeichert). Ich vermute das könnte man hier ändern, aktuell kann ich nur settings speichern wenn ich vorher segmentieren lasse.

2024-07-02 15:24 UTC, sonjajk commented on cellpose/gui/gui.py
> +        self.saveSettings.setEnabled(False)
Ja, das ist genau, was ich oben meinte. Was denkst du denn, wie es gewünscht ist? Dass man die Settings einfach immer speichern kann? Oder dass sie nur gespeichert werden können, wenn sie von den initialen Einstellungen abweichen?

2024-07-02 16:00 UTC, Davidundso commented on cellpose/gui/gui.py
> +        self.saveSettings.setEnabled(False)
Die settings sollten immer gespeichert werden können

2024-07-04 11:05 UTC, robertkrasniqi approved these changes

2024-07-07 10:48 UTC, Davidundso approved these changes
Die Änderung wurde vorgenommen. Danke!

2024-07-09 15:58 UTC, merged