30 new export option .csv
claassenlab/cellpose pull request #58
Opened 2024-07-16 11:59 UTC by RukiyyeE

resolves #30 

## Description

Files can now be exported as CSV files in the same directory through the new "Save Features as .csv" option in the "File" dropdown menu. The files keep their name and get the suffix "_cp_features.csv" added.

## Changes

The files cellpose/gui/io.py, cellpose/gui/menus.py, cellpose/io.py were modified.

 - `_save_features_csv(parent)` calls `save_features_csv(parent.filename`) if the dataset is two-dimensional (parent.NZ == 1) to save feature data in a CSV file. Otherwise, it outputs an error message.
 -  `save_features_csv(file_name)` creates or overwrites a CSV file named filename_cp_features.csv without saving content.
 -  a ´Save Features as .csv´button` was added to the dropdown menu.
     -   `shortcut: Ctrl+C` was created for this option.

## Testing 
The function can be tested by uploading an image and then clicking Save Features as .csv in the File menu.

2024-07-16 14:49 UTC, jakobjo commented on cellpose/gui/io.py
> +    filename = parent.filename
I would recommend an error message or an exception, if there is no file loaded atm.

2024-07-16 20:27 UTC, mariehartung requested changes
## Main Review
Nice implementation! It's great that you were able to implement this so quickly even though you were sick! 

### Proposed changes

1. I agree with Jakob, an exception in case of a missing file would be a good idea. As of now, I get an error message if I try to use this feature without a picture loaded:
![image](https://github.com/user-attachments/assets/f9b30dc2-beac-465b-93d4-9250ec8e3f27) 
This doesn't really affect anything as far as I can see and the user probably won't notice it, but it is not ideal.

2. I am also not quite happy with the shortcut, but I also can't really think of a better one, since "Ctrl+S" is already taken and "Ctrl+V" bears the same problem... Maybe a combination with Shift might be worth considering?

3. This was not part of the issue so I won't insist on this, but it might be better to ask if the user wants to replace the file before removing it.

### Nitpicks
Some minor changes of comments (see individual comments).

2024-07-16 20:27 UTC, mariehartung commented on cellpose/gui/io.py
> +    if parent.NZ == 1:
A comment what "parent.NZ == 1" means might be helpful

2024-07-16 20:27 UTC, mariehartung commented on cellpose/io.py
> +        os.remove(file_name)
It might be nice to ask the user if they really want to replace the file before removing it

2024-07-16 20:27 UTC, mariehartung commented on cellpose/gui/menus.py
> +    parent.saveFeaturesCsv.setShortcut("Ctrl+C")
Shortcut not ideal because it is usually reserved for copying (though I don't have a better idea at the moment either)

2024-07-16 20:27 UTC, mariehartung commented on cellpose/io.py
> +    """ save features to .csv file and remove if it already exists
Really, really tiny nitpick, but I would put a line break after the quotation marks for consistency

2024-07-20 10:26 UTC, mariehartung approved these changes

2024-07-20 10:29 UTC, mariehartung submitted a review, later dismissed
### Approval
Thank you very much for implementing the changes!
Everything works perfectly: The error is displayed if no image is opened and the new shortcut is better and successfully creates a file.

2024-07-22 21:57 UTC, mariehartung approved these changes
## Main Review
Nice implementation! It's great that you were able to implement this so quickly even though you were sick! 

### Proposed changes

1. I agree with Jakob, an exception in case of a missing file would be a good idea. As of now, I get an error message if I try to use this feature without a picture loaded:
![image](https://github.com/user-attachments/assets/f9b30dc2-beac-465b-93d4-9250ec8e3f27) 
This doesn't really affect anything as far as I can see and the user probably won't notice it, but it is not ideal.

2. I am also not quite happy with the shortcut, but I also can't really think of a better one, since "Ctrl+S" is already taken and "Ctrl+V" bears the same problem... Maybe a combination with Shift might be worth considering?

3. This was not part of the issue so I won't insist on this, but it might be better to ask if the user wants to replace the file before removing it.

### Nitpicks
Some minor changes of comments (see individual comments).

2024-07-24 09:24 UTC, NicolasDelgadoL reviewed
The button works and creates a file that lands in my Desktop, the appropriate messages are printed when saving a file or when this is not possible. The keyboard shortcut is also functional. Nothing to add, very nice job!!

2024-07-24 09:25 UTC, NicolasDelgadoL approved these changes

2024-07-24 13:59 UTC, merged