44 curser position information on mouseclick
claassenlab/cellpose pull request #61
Opened 2024-07-18 06:49 UTC by RukiyyeE

resolves #44 

## Description
When clicking on the minimap, the mousePressEvent is triggered, capturing and storing the coordinates of the clicked position. The stored coordinates are used in Ticket 45 to enable navigation in the image via the minimap.

## Changes
- overrode `mousePressEvent` in the `MinimapWindow` class
- normalized coordinates and saved the x-coordinate in `normalized_x` and the y-coordinate in `normalized_y`
- saved coordinates in `self.lastClickPos` and the normalized ones in `self.normalizedClickPos`

## Testing

2024-07-18 11:03 UTC, NicolasDelgadoL requested changes
So far its looking very good! The method overrides the mousePressEvent, it has a clear description, the positions of the click are stored in variables with clear names and there's a block to normalize the resulting values, so all acceptance criteria are addressed. There are, however, some details worth pointing out.

There is an error message that pups up regarding a call of "toggle.minimap()" in guy.py. I asume this is just something that slipped through from previous versions, it would be nice to take it out and use a call "self.minimap_window()" instead, as in the main branch. 

For testing the normalization, I added the statement: 

        print("Normed positions x, y: " + str(self.normalizedClickPos))

at the end of the method. The values returned are not within 0 and 1 as we want them to, for instance, clicking at approx. the center of the minimap delivers: 

"Normed positions x, y: (245.9..., 194.9...)". 

It seems that setting parenthesis around the subtraction: 

normalized_x = (viewboxPos.x() - 9) / self.viewbox.width()
normalized_y = (viewboxPos.y() - 9) / self.viewbox.height()

solves this issue, so I would suggest adding those, too :) 

Other than that, the method seems to work very well 👍

2024-07-18 11:48 UTC, jakobjo commented on cellpose/gui/guiparts.py
> +        self.viewbox.autoRange()
Is this a spaceholder? There should be no updating of the minimap viewbox in this method imo, only of the mainW viewbox. This is part of ticket 46.

2024-07-21 16:37 UTC, NicolasDelgadoL reviewed
Hello, 

I went ahead and added the line: 

self.setWindowFlags(self.windowFlags() | QtCore.Qt.WindowStaysOnTopHint)

to the MinimapWindow class constructor. This line prevents the minimap to go to the background (in Mac at least) and is present in other branches but missing here. 

Other than that, the previous change requests were addressed and it all works very well now, I would approve 👍 :)

2024-07-21 16:37 UTC, NicolasDelgadoL submitted a review, later dismissed

2024-07-21 19:52 UTC, mariehartung reviewed
### Main Review
First of all, great implementation! It is concise and comprehensible, and works exactly like it is supposed to. Great job!

**Small possible changes**
I would merely change the description slightly to make it even more understandable for future users (see individual comments).

2024-07-21 19:52 UTC, mariehartung commented on cellpose/gui/guiparts.py
> +        This method is triggered when the user clicks on the minimap,
I would add that a left mouse click is required (since we also use the right click (for the adjustment in the former ticket 11))

2024-07-21 19:52 UTC, mariehartung commented on cellpose/gui/guiparts.py
> +        """
You might also add that it returns normalized x and y positions

2024-07-22 10:41 UTC, mariehartung submitted a review, later dismissed
### Approval
Thank you for updating the documentation, I have nothing else to add!

2024-07-22 17:26 UTC, NicolasDelgadoL commented
From my side also no further comments, great job 💯

2024-07-22 17:26 UTC, NicolasDelgadoL submitted a review, later dismissed

2024-07-22 21:56 UTC, mariehartung approved these changes

2024-07-23 15:14 UTC, NicolasDelgadoL approved these changes

2024-07-23 15:59 UTC, RukiyyeE commented
Thank you for your reviews! I will now merge this PR.

2024-07-23 16:01 UTC, merged